// Code generated by "stringer -type=ExitCode"; DO NOT EDIT.

package nagios

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[WARNING-1]
	_ = x[CRITICAL-2]
	_ = x[UNKNOWN-3]
	_ = x[DEPENDENT-4]
}

const _ExitCode_name = "OKWARNINGCRITICALUNKNOWNDEPENDENT"

var _ExitCode_index = [...]uint8{0, 2, 9, 17, 24, 33}

func (i ExitCode) String() string {
	if i < 0 || i >= ExitCode(len(_ExitCode_index)-1) {
		return "ExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitCode_name[_ExitCode_index[i]:_ExitCode_index[i+1]]
}
